Parameters:
  ImageId:
    Type: String
    Description: "AMI ID of the instance to be created."
  mySubnet:
    Type: AWS::EC2::Subnet::Id
    Description: "Subnet ID where the instance will be launched."
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: "Security group ID to associate with the EC2 instance."
  InstanceType:
    Type: String
    Description: "Type of EC2 instance to be created."
  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of the key pair to use for the EC2 instance."
  InstanceName:
    Type: String
    Description: "Name tag for the EC2 instance."
  
Resources:
  myEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId:  !Ref ImageId
      KeyName: !Ref KeyPair
      SubnetId:
        Ref: mySubnet
      SecurityGroupIds: 
        - Ref: InstanceSecurityGroup
      Tags:
        - Key: "Name"
          Value: !Ref InstanceName
        