Parameters:
  InstanceName:
    Type: String
    Default: myInstance
    MaxLength: 20

  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - m1.small
      - m1.large
    Description: Enter t2.micro, t2.small, t2.medium, m1.small, or m1.large. Default is t2.micro.

  KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Default: kops_key

  VPNConnection:
    Type: String
    Default: Poland
    AllowedValues:
      - Poland
      - Germany
    Description: Select current location of VPN server
    
Outputs:
  InstanceName:
    Description: "Instance Name"
    Value: !Ref InstanceName
    Export:
      Name: "InstanceName"
  InstanceType:
    Description: "Instance Type"
    Value: !Ref InstanceType
    Export:
      Name: "InstanceType"
  KeyPair:
    Description: "Key pair"
    Value: !Ref KeyPair
    Export:
      Name: "KeyPair"
  VPNConnection:
    Description: "VPN country"
    Value: !Ref VPNConnection
    Export:
      Name: "VPNConnection"
  